# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_models.ipynb.

# %% auto 0
__all__ = ['push_fastai_learner']

# %% ../04_models.ipynb 3
import os,json,subprocess, shutil
import re
from fastcore.utils import *
from .core import *
from .datasets import *
from .competition import *
# from fastcore.all import *

# %% ../04_models.ipynb 5
def push_fastai_learner(learner, # Fastai Learner
                        model_fname, # ie `model1.pkl`
                        version_comment, # dataset versioning
                        cfg_path='.'
                ):
    '''Exports a learner and updates kaggle dataset'''
    cfg = get_config_values(cfg_path)
    
    local_path = Path(cfg_path)/cfg['data_path']/cfg['model_dataset_name']
    ds_slug = f"{cfg['datasets_username']}/{cfg['model_dataset_name']}"
    
    print(f"-----Downloading or Creating Dataset if needed")
    if local_path.exists(): pass
    elif ds_exists(ds_slug): get_dataset(ds_slug,str(local_path))
    else:                    mk_dataset(local_path,cfg['model_dataset_name'])
    
    print(local_path)
    orig_path = learner.path
    learner.path = local_path.parent
    learner.export(model_fname)
    learner.path = orig_path
    push_dataset(local_path,version_comment)
    print(f"{ds_slug} update complete")
